name: photo_view
description: Photo View provides a gesture sensitive zoomable widget. Photo View is largely used to show interactive images and other stuff such as SVG.
version: 0.14.0
homepage: https://github.com/renancaraujo/photo_view

environment:
  sdk: ">=3.3.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: 1.25.2
  flutter_test:
    sdk: flutter
